### ISSUE TITLE
不会使用

### ISSUE THREAD

**Issue by CHENJINWEN33** [ZetaSp/GHDTranslator.py#1]
@ZetaSp 老铁第一次玩github，这个怎么汉化的求教

**Comment by zetaloop** [comment]
这个项目现在暂时没做完（咕了半年了），现在学校两周放一次没空回家，要做完得稍后了
如果要使用的话，[项目主页](https://github.com/ZetaSp/GHDTranslator.py)右上角 Code，download zip 下载下来解压就是代码
执行主文件 GHDTranslator.py 即可，程序会自动检查目录哪个要翻译，按提示选择
（做了一半，指不定有bug没修）
依赖模块 alive_progress 和 readchar，记得 pip 装一下

**Comment by zetaloop** [comment]
github 上好像有其他 ghd 汉化也可以试试

**Comment by CHENJINWEN33** [comment]
好的非常感谢
